### ISSUE TITLE
Issue with executing  ./setup.sh

### ISSUE THREAD

**Issue by residual-07** [MicrosoftLearning/mslearn-azure-ml#89]
# Module: 06
#### Step: 6.

Description of issue

Execution of the ./setup fails to create resources within resource group for Azure ML studio. Throws Validation error and it also won't provision the aml cluster. Snippet of the message: Code: Validation Error Message: Missing dependent resources in worspace json 
![Screenshot 2024-05-23 at 11 20 57 AM (2)](https://github.com/MicrosoftLearning/mslearn-azure-ml/assets/124274176/974b8f9a-b959-4efe-856f-3988e9105296)

Im unable to provide Repro code, so will attach screenshot

**Comment by LewisGoDeploy** [comment]
I have experienced the same in more than 1 of these labs.

**Comment by raduhackit** [comment]
Hi folks,
there seems to be nothing wrong with the setup.sh, i had the same issue today. Apparently this is a bug in the ml extension version 2.26 (see here: https://github.com/Azure/azure-cli/issues/28980)
some folks recommend downgrading the ml extension version to 2.25 which should solve the problem for now. Did not try it myself.
cheers

**Comment by meet47** [comment]
Hi, Does anyone got the solution or recommendation for the issue?

**Comment by ramkcvs** [comment]
> Hi folks, there seems to be nothing wrong with the setup.sh, i had the same issue today. Apparently this is a bug in the ml extension version 2.26 (see here: [Azure/azure-cli#28980](https://github.com/Azure/azure-cli/issues/28980)) some folks recommend downgrading the ml extension version to 2.25 which should solve the problem for now. Did not try it myself. cheers

Folks is there a solution to this problem? How to lower ml extn version on bash ?

**Comment by varunotelli** [comment]
Instead of using the cloud shell terminal i used the terminal in my vs code and used the 2.13.0 version. 
You can do this by typing the following commands:
`az extension remove -n ml`
`az extension add -n ml --version 2.13.0`

**Comment by LewisGoDeploy** [comment]
I've not been able to use a lesser version by running commands in Cloudshell/Bash. Is there a way this can be done instead of installing Visual Studio code as suggested above?

Error I get is:

Cannot remove system extension ml in Cloud Shell.

Default enabled including preview versions for extension installation now. Disabled in future release. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
Extension 'ml' 2.26.0 is already installed.

**Comment by madiepev** [comment]
There seems to be a problem with Cloud Shell in general, which is why commands/scripts don't work. We're actively investigating the issue and will update here when there's a fix. The current "quick" workarounds are to create all resources manually (as the scripts are only used here to speed up the setup), or indeed to use the CLI locally through an IDE like VS Code, where you can specify the version you want to use.

**Comment by achauhan-scc** [comment]
ml extension 2.26.1 is released with the fix.

**Comment by madiepev** [comment]
**UPDATE**

The fix in the CLI ML extension seems to be fixed in the newest version. As you may have noticed however, you can't update the extension yourself in the Cloud Shell (you can when working locally). The extension will be updated in the next scheduled update of the Cloud Shell. We expect this fix to happen end of this week. Hopefully, next week the setup scripts should work again. Until then, the quickest workaround is to create the necessary resources manually through the portal instead of using the Cloud Shell.

**Comment by ramkcvs** [comment]
> **UPDATE**
> 
> The fix in the CLI ML extension seems to be fixed in the newest version. As you may have noticed however, you can't update the extension yourself in the Cloud Shell (you can when working locally). The extension will be updated in the next scheduled update of the Cloud Shell. We expect this fix to happen end of this week. Hopefully, next week the setup scripts should work again. Until then, the quickest workaround is to create the necessary resources manually through the portal instead of using the Cloud Shell.

Dear Collaborator,
thanks for the feedback, Seems the problem still exists as the version 2.26.0 is still to be replaced with 2.26.1... 
"[ ~ ]$ az extension add -n ml -y
Default enabled including preview versions for extension installation now. Disabled in future release. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
**Extension 'ml' 2.26.0 is already installed."**

**Comment by madiepev** [comment]
Hopefully the update has rolled out to everyone's Cloud Shell now and the setup scripts work again!

**Comment by SkillableKA** [comment]
Unfortunately this issue still seems to be present. We have multiple tickets open due to the setup.sh file throwing the same errors above. I have provided a workaround using VS Code to get them through the lab, but wanted to make you aware the issue still persists with how the instructions are written.

CloudShell is running the latest ml 2.27.0 and az-cli is up to date at 2.62.0:

<img width="566" alt="image" src="https://github.com/user-attachments/assets/34af063a-6455-47c4-af7f-a0b44f2bacbd">
<img width="927" alt="image" src="https://github.com/user-attachments/assets/7c67ca7a-dd07-4cf1-8f12-9a03bdb233d5">
<img width="928" alt="image" src="https://github.com/user-attachments/assets/3049ff2d-e24f-4d6d-afa2-01088768c943">

**Comment by madiepev** [comment]
Issue seems to be back. Support has been contacted. I'll update when I have more information. As a workaround, workspace can be created manually through the UI in the Azure Portal.

**Comment by madiepev** [comment]
ML version 2.28 will have the patch that fixes this issue again. You can use az version to check your ML extension version. If you have a lower version, you can create the necessary resources manually. Since this is a product bug that should be resolved for all cloud shells within 1-2 weeks, I'm closing the issue again.
