### ISSUE TITLE
Explainer functionality in UI has changed and instructions do not reflect changes

### ISSUE THREAD

**Issue by Jason-Microsoft-MTT** [MicrosoftLearning/mslearn-azure-ml#97]
#### Step: 07

Description of issue
Original Instructions:
The Models tab will show all models that have been trained. Select View explanation for the best model to understand which features influenced the target value the most.

Issue: The UI and functionality has changed. After running the AutoML experiement, model explanation is initiated in the portal for each model, it doesnt just offer explainability for the best model. Also, once the explain is initited, it creates a new job and based on observations, it runs explainer twice and RAI dashboard once. The explainations are available after about 5 min., the RAI dashboard takes 15 min. Im not sure if the product team is aware that both operations are running on this selection and would result in unnecessary computational expense and unnecessary features created.

Here are supporting images:
![image](https://github.com/user-attachments/assets/36d9a4b2-1e49-4ac9-96f8-e649a0b27f7e)
![image](https://github.com/user-attachments/assets/9f832f7d-040e-4b55-a89a-e3a88f43cee4)
![image](https://github.com/user-attachments/assets/b9fcd54e-934b-45fc-985e-08cd0c64f89b)

**Comment by afelix-95** [comment]
Thanks for pointing that out! The instructions are updated to reflect the changes in UI. 

As for the child jobs being generated, AzureML Studio will only run these additional jobs for the model with highest accuracy by default. If we select any other algorithm, it'll generate only one child job for explanation and no Responsible AI dashboard is created. 
Since the explanation dashboard becomes available independently of the RAI job run, for the scope of the exercise, the RAI dashboard can be ignored and you don't have to wait for its job to finish.
